CREATE DATABASE IF NOT EXISTS quizWebsite;
USE quizWebsite;


CREATE TABLE Users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password_hash VARCHAR(256) NOT NULL,
    hash VARCHAR(64) NOT NULL,
    join_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);